services:
  ollama:
    image: ollama/ollama:latest
    container_name: study-buddy-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    networks:
      - study-buddy-network
    healthcheck:
      test: ["CMD-SHELL", "ollama list || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

  study-buddy-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: study-buddy-api
    ports:
      - "1000:1000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - study-buddy-network
    environment:
      - PYTHONPATH=/app
      - OLLAMA_BASE_URL=http://ollama:11434
      - SERVICE_MODE=api
    command: ["python", "main.py", "--mode", "api"]
    depends_on:
      ollama:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:1000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  study-buddy-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: study-buddy-web
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - study-buddy-network
    environment:
      - PYTHONPATH=/app
      - OLLAMA_BASE_URL=http://ollama:11434
      - SERVICE_MODE=web
    command: ["python", "main.py", "--mode", "web"]
    depends_on:
      ollama:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8501 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  ollama_data:
    driver: local

networks:
  study-buddy-network:
    external: true
    name: study-buddy-network

